### ISSUE TITLE
"Save" icon?

### ISSUE THREAD

**Issue by akalajzi** [primer/octicons#115]
I might just be blind, but is there really no save, or save-like icon? You know, with a little diskette and maybe an arrow pointing in. Or just a diskette.

**Comment by shurcooL** [comment]
The closest one I can see is https://octicons.github.com/icon/desktop-download/.

**Comment by aaronshekey** [comment]
We don't use the disk as a metaphor for save since it's outdated technology. Many people have been born long after disks were a thing...

The closest we have to "save" is https://octicons.github.com/icon/cloud-upload/, though if your UI is dependent on the notion of "Saving", I think your best bet a button with clear text that says "Save".

**Comment by akalajzi** [comment]
Yeah, but there's still plenty of "saving" going on (ie, saving settings or any kind of input; saving that doesn't happen automatically, but requires user to initiate still has plenty of use cases), diskette is just a symbol that stuck, even though no one uses diskettes anymore :). I mean, all symbols are just that - symbols. No one uses books to keep code, repo symbol is like a book. No one uses analogue bells, its a notification symbol here on github. Etc, you get the point.

Both desktop download and cloud upload are wrong/lying to the user; depending on context. But anyway, yeah, I went with "save" text inside a button, with all other buttons being icons. Super weird.
