### ISSUE TITLE
Questions on exporting svg from Sketch

### ISSUE THREAD

**Issue by cpylua** [primer/octicons#135]
Seems Sketch always exports svg files with `fill-rule=evenodd`, while the TrueType font only supports the `non-zero` fill rule.

Some of my icons are incorrectly filled on iOS Safari, because the `fill-rule` in svg file is ignored by Fontello when generating font files. You mentioned you are using fontello's libraries to generate font files in Issue #24.

So do you use `Layer -> Paths -> Reverse Order` in the Sketch file to manually fix incorrect contour direction in the generated font files?

**Comment by jonrohan** [comment]
The svg files in the `/lib/` folder are raw output from Sketch. We use a grunt build process that minifies the svg files and puts them in a `/build/` directory. This directory isn't checked into the repository because of the likelyhood of conflicts. The `/build/` directory is published to npm https://unpkg.com/octicons@4.4.0/build/svg/

You can also build the icons yourself https://github.com/primer/octicons#building-octicons if you'd like.

**Comment by cpylua** [comment]
Thanks!
