### ISSUE TITLE
Normal install without npm?

### ISSUE THREAD

**Issue by deanishe** [primer/octicons#152]
I'd like to use Octicons in a site, but I can't seem to find a "normal" distribution with just the CSS and font files. The docs only talk about `npm` and node, which I'm not using.

Am I missing something?

**Comment by m1guelpf** [comment]
@deanishe I add them including the file using a CDN and then show it with span tags.

**Comment by deanishe** [comment]
@m1guelpf Thanks very much. I found the same CDN after a bit of googling and downloaded the CSS and fonts from there. Working nicely now without loads of node crap.

Is there a reason there isn't an "official" CSS+font bundle?

**Comment by jonrohan** [comment]
> Is there a reason there isn't an "official" CSS+font bundle?

We stopped supporting the font bundle, because using font icons [are a bad pattern](https://cloudfour.com/thinks/seriously-dont-use-icon-fonts/) and we want to discourage using them.

For using these icons without NPM, I would recommending using a [spritesheet](https://github.com/primer/octicons#spritesheet) you can see the compiled spritesheet in [the spritesheet demo](https://unpkg.com/octicons@5.0.1/build/sprite.octicons-demo.html)

Then you can simply include the icon using the `<use` tag, for example:

```html
<svg version="1.1" width="20" height="32" viewBox="0 0 10 16" class="octicon octicon-zap" aria-hidden="true">
    <use xlink:href="#zap" />
</svg>
```
