### ISSUE TITLE
Fix Circle-Slash icon

### ISSUE THREAD

**Issue by heyneff** [primer/octicons#199]
The circle-slash feels like it's being used as a No symbol. If it is, it should be rotated 90°.

<img width="614" alt="octicons-cirlce-slash" src="https://user-images.githubusercontent.com/3827051/36861511-efbfe0ee-1d38-11e8-96ec-6ccfaba6d9fd.png">

https://en.wikipedia.org/wiki/No_symbol
<img width="172" alt="from-wikipedia" src="https://user-images.githubusercontent.com/3827051/36861554-115b4590-1d39-11e8-8d1f-c519e617796d.png">

**Comment by shurcooL** [comment]
From that wikipedia article:

> also known as **circle-backslash** symbol

The octicon is named **circle-slash**, which makes its current look more appropriate.

Where is the circle slash octicon is used? Is it used to show things are prohibited?

https://octicons.github.com/icon/no-newline/ is somewhat similar, but it's used to show that a newline is missing, not that it's prohibited.

**Comment by shurcooL** [comment]
> Where is the circle slash octicon typically used?

Oh, I've remembered now. It's usually used to illustrate a "closed event", when an issue or PR is closed, e.g.:

![image](https://user-images.githubusercontent.com/1924134/36876052-0a453458-1d81-11e8-92a3-f4da2a07f212.png)

Yeah, prohibition sign doesn't seem very applicable to that. The current version seems like a better fit for a "closed event".

**Comment by jonrohan** [comment]
It's been a while since we originally designed them, so I'm unsure of the original intent of the `circle-slash` It's very probable that we did mean it to be slashed to the left. 

I would categorize this as a bug. But I don't think it's confusing our users, or at least I haven't heard reports about it. 

Ultimately, date unknown, we would like to launch an initiative to more intelligently design all of the icons. I'll make sure this issue is raised when that happens.
