### ISSUE TITLE
Make it more obvious where people can download the SVG files

### ISSUE THREAD

**Issue by jonrohan** [primer/octicons#214]
I want to avoid checking SVG files into this repository. I feel strongly that having it here to, the confusion of where to contribute to Octicons increases.

However we need to address questions like https://github.com/primer/octicons/issues/213

In my ideal world, we would include in the release script a line that zips up the `/build/` folder and attaches it to a release on this repository. Allowing people to simply download svg files.

**Comment by cyberalien** [comment]
Maybe mention in documentation that to get SVG files users should run `npm install octicons` instead of cloning this repository?

Downloading zip files from website is a hassle, I'm sure many like me are looking for automated way to get SVG files and keep it up to date. NPM is great way of doing it, all that needs to be done is mention that NPM repository exists.

**Comment by colebemis** [comment]
The SVGs are now available in the GitHub repo: https://github.com/primer/octicons/tree/master/icons

You can also download individual SVGs on the website: https://primer.style/octicons
