### ISSUE TITLE
`verified` icon looks misaligned

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [primer/octicons#296]
It looks like background cloud is misaligned. Or is it by design?
<img width="20%" src="https://user-images.githubusercontent.com/15037839/53298013-a04d6580-3840-11e9-9c1c-b2c72f970d80.png"/>

It showed up when I sent a message to GitHub.
![image](https://user-images.githubusercontent.com/15037839/53298075-9841f580-3841-11e9-9e36-66c4705b33c6.png)

**Comment by OrkhanAlikhanov** [comment]
Same for [`unverified`](https://octicons.github.com/icon/unverified) too.

**Comment by ashygee** [comment]
Thanks for letting us know @OrkhanAlikhanov! It looks like there could be an issue with the `viewbox` for these icons. I’ll go ahead and look into this right away and update soon.

**Comment by ashygee** [comment]
Hey @OrkhanAlikhanov I've looked into this and it appears that the icons were aligned at `-0.01` and also sized to `16.01` for width and height which caused the viewbox to expand to `17` instead of `16`

`<svg width="17" height="17" viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg">`

I'm going to create a PR to update these to the correct sizing and that should fix everything. 😺 

CC @jonrohan

**Comment by jonrohan** [comment]
Fixed in https://github.com/primer/octicons/pull/299
