### ISSUE TITLE
PR marked as draft

### ISSUE THREAD

**Issue by brianlovin** [primer/octicons#477]
### What should the icon represent?

Related to #376, whenever we have a better icon for draft PRs, we need to update this:

<img width="938" alt="Screen Shot 2020-07-20 at 9 00 45 PM" src="https://user-images.githubusercontent.com/1923260/88008090-aa72a280-cacc-11ea-8086-8dbeef858116.png">

### Where will the icon be used?

PR timeline views whenever a PR is moved from Ready to Review → Draft

**Comment by edokoa** [comment]
Linking this from our icons inbox!

**Comment by sophshep** [comment]
I know @Juliusschaeper had some good ideas for this!

**Comment by edokoa** [comment]
Linking the PR redesign by @Juliusschaeper 

https://github.com/github/design-systems/issues/873

**Comment by Andre601** [comment]
I hope I'm allowed to talk here (Sorry if there's a better place for it).

But when the icon would be changed should perhaps the icon for the Draft PR itself (The one shown as Icon in PR list and such) be changed to, as the only difference to the normal icon is a basic color change (gray instead of green) which is not useful, especially in terms of availability, as colorblind people couldn't distinguish this from the icon alone.

Perhaps a possible idea would be the PR icon, but the right arrow would have a dotted line instead of a solid one?

**Comment by ashygee** [comment]
This work is being tracked here: https://github.com/github/design-systems/issues/1286
