### ISSUE TITLE
Strikethrough [Icon Request]

### ISSUE THREAD

**Issue by brianlovin** [primer/octicons#503]
### What should the icon represent?

Strikethrough on the markdown bar

### Where will the icon be used?

GitHub mobile apps

**Comment by ashygee** [comment]
@brianlovin what is the timeline for this icon?

**Comment by brianlovin** [comment]
No timeline, we are fine to de-pri.

**Comment by edokoa** [comment]
It's pending internal review, but we're considering this one.

![image](https://user-images.githubusercontent.com/694831/99803985-9900dc00-2b3a-11eb-9272-aadb5b1a92be.png)
![image](https://user-images.githubusercontent.com/694831/99804011-a1f1ad80-2b3a-11eb-8e44-f53665d08382.png)

**Comment by brianlovin** [comment]
Why did you choose the letter T for this one? It does feel like most strikethrough representations always use the later S.

**Comment by edokoa** [comment]
Hi, we were working on using the `S`

![image](https://user-images.githubusercontent.com/694831/100245340-3b083600-2f38-11eb-955c-66726bc008ca.png)

The problem with it is that it becomes more illegible if we try to follow the rules of the icons. Normally we use a space around overlapping objects. We could choose to not apply this "buffer"

![image](https://user-images.githubusercontent.com/694831/100245492-612dd600-2f38-11eb-88aa-126eb36ebac4.png)

But if we apply the spaces, the character becomes illegible:

![image](https://user-images.githubusercontent.com/694831/100245907-d7323d00-2f38-11eb-9826-9c256af6653b.png)

I was trying the T because it works with the buffer and I also saw it was kind of common (not as much as the s). We can discuss this and reconsider what works better here.

**Comment by ashygee** [comment]
@brianlovin we also felt safe with "T" because it is also common in iconography for strikethrough. Here are some examples:

![strikethrough icons using the letter T, S, and ABC](https://user-images.githubusercontent.com/10384315/100254645-6b7bb000-2ef7-11eb-81d1-3c480816074c.png)

**Comment by edokoa** [comment]
@brianlovin we were talking a little bit more about this, and @colebemis suggested we try to connect the strikethrough to the main element in the bottom part to be consistent.

![image](https://user-images.githubusercontent.com/694831/100257081-d0f68d80-2f45-11eb-8730-cd7d1aa8cd06.png)

We're all fine with this version. What do you think?

**Comment by brianlovin** [comment]
Love it, that looks good to me!

**Comment by edokoa** [comment]
I'll work on the final 16 / 24 versions

**Comment by edokoa** [comment]
**32px**

![image](https://user-images.githubusercontent.com/694831/100632747-81d99f80-332d-11eb-9223-484c9726e4c4.png)

![image](https://user-images.githubusercontent.com/694831/100632781-8aca7100-332d-11eb-9211-3690783d0ea5.png)

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=5378%3A777

**48px** 

![image](https://user-images.githubusercontent.com/694831/100631267-d24ffd80-332b-11eb-8179-242cd22e15c8.png)

![image](https://user-images.githubusercontent.com/694831/100631207-c2381e00-332b-11eb-92ec-a33998afc5d6.png)

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=5378%3A612

**Comment by ashygee** [comment]
These are great @edokoa!! We can do one last review Wednesday 😄

**Comment by ashygee** [comment]
Published in [11.2.0 release](https://github.com/primer/octicons/releases/tag/v11.2.0)
