### ISSUE TITLE
Enclosed person icon

### ISSUE THREAD

**Issue by brianlovin** [primer/octicons#505]
We're looking for an enclosed person icon to use in the mobile apps, where the app will have more weight than our current icon, and in a "selected state" will feel equally weighted to other filled icons, like Notifications and Home.

SF Symbol for general direction:
![image](https://user-images.githubusercontent.com/1923260/98152428-8f168200-1e86-11eb-9d7e-3b9ed4a81f0b.png)

**Comment by colebemis** [comment]
Slack discussion for context: https://github.slack.com/archives/CK6071T4N/p1604353463395300

**Comment by ashygee** [comment]
@brianlovin what is the timeline for this icon and can you also provide mocks of the screens so we can see what the current icon is that you're referring to? We will be able to offer a better recommendation/solution with more visual context. Thank you!

**Comment by brianlovin** [comment]
We'll need it by the end of November. Mocks are private, but that Slack link should get you to our internal discussion to talk about this 😊

**Comment by ashygee** [comment]
Just checked in with @brianlovin on this one and this is still needed.

Notes:

> esp in the selected state - the weights are unbalanced compared to notifications/home which get a more heavy filled state

**Comment by ashygee** [comment]
Closing this for now as we assess how the Explore feature will also be iterated on. Because both icons currently use only the stroke version, we want to strategize how this might fit to have a filled version for both. There are already complications with having an enclosed person because when the icon is filled the avatar/person is optically smaller and doesn't offer the same balance.
