### ISSUE TITLE
[Icon request]

### ISSUE THREAD

**Issue by bradley2083** [primer/octicons#545]
Love your icons.  Using them in a project that's still just local at this point, but would love to have the following icons to stick with just using your icons vs. mixing/matching.   

**Social package:**
- Instagram
- Facebook
- Twitter
- Youtube
- Pinterest
- Linkedin
- Dribbble

**Shop:**
- Cart 
- Basket
Hoping to go live with my project by mid March. 

Thanks for considering!

**Comment by ashygee** [comment]
Hey @bradley2083 thanks for the compliment and the requests! Because Octicons are a part of GitHub's visual language, we focus on adding icons to our system that best suit the needs of GitHub. As of now, we don't have plans to include other social icons or shopping themed icons. I might suggest taking a look at [Feather icons](https://feathericons.com/), which is another great open source icon project, and their look/feel is also similar to octicons.
