### ISSUE TITLE
[Icon request] repo-private

### ISSUE THREAD

**Issue by vdepizzol** [primer/octicons#556]
#### What should the icon represent?

A private repository. We'd like to distinguish a public from a private repository without using a generic `lock` icon, so the icon can describe what type of object it is regardless of the context.

#### Where will the icon be used?

Any pages that currently use the `lock` icon to represent private repositories — including section headers, navigation, lists etc.

#### What is the timeline? Is this critical for a launch event?

Not driven by a specific timeline — improvement suggestion to be considered for future navigation improvements.

#### Screenshots

<img src="https://user-images.githubusercontent.com/293280/109718654-6ebcb280-7b5c-11eb-9754-9542223361d2.png" alt="Current iteration" width="261">

![Screen Shot 2021-03-02 at 13 32 35](https://user-images.githubusercontent.com/293280/109718113-c27acc00-7b5b-11eb-9ebb-707e0847cc22.png)

Current explorations can be found here:
https://www.figma.com/file/w1hqcWPtxx9JPabkmX23ux/Navigation-breadcrumb-quick-patches?node-id=53%3A484 (Internal to GitHub staff)

**Comment by ashygee** [comment]
Thanks for the request @vdepizzol, I'm adding this to our octicons board for discussion in our sync tomorrow. From what I saw in the figma you shared, my only concern is the modifier on the repo book.

| Images |
|--------|
| ![image](https://user-images.githubusercontent.com/10384315/109722406-8185b600-7b61-11eb-8b1c-3daf7cc637f9.png) |
| ![image](https://user-images.githubusercontent.com/10384315/109722446-8cd8e180-7b61-11eb-9452-08f50dbc7052.png) | 

Here is a comparison between the filled lock and a stroke version that @vdepizzol had in his file. Because he's using the filled lock here we should discuss if this is a direction we want to move in for modifiers. We need to test how this looks on non-retina displays because I'm afraid it might appear a bit muddled.

**Comment by ohjoycelau** [comment]
Saw this issue just wanted to throw in I think this would be very helpful! Here is a snippet of how my mocks have been lately dealing with private repositories (and private memexes too for that matter):

<img width="1209" alt="Screen Shot 2021-03-02 at 2 33 15 PM" src="https://user-images.githubusercontent.com/6744014/109724503-8a2bbb80-7b64-11eb-80b5-2914b7d313d7.png">

Many enterprise customers have a majority of their repositories (and projects) as private. It gets real old, real soon when you have the `private` label over and over again or only the generic lock icon.
