### ISSUE TITLE
trouble downloading/working on the given svgs

### ISSUE THREAD

**Issue by miadotcx** [primer/octicons#561]
I tried downloading the SVGs, which displayed properly in my browser, and when I look at the xml, I can see nothing wrong with them, but importing them into illustrator simply results in them showing up as a single vector, without any styles.

this is disappointing as i was looking to export a higher res PNG selection for discord emotes.

hope i can get help with this.

**Comment by ashygee** [comment]
Hi @miadotcx, thanks for citing this issue for us. When we add octicons we strip unnecessary SVG metadata but it appears that some of that might be needed by Illustrator to render the octions.

As of now, our team uses Figma and because we are not actively using Illustrator this is not something we plan on working on soon. What I can recommend is that if you do use Figma  you can access the [Octicons library](https://www.figma.com/community/file/809920999413919915/Octicons---GitHub's-icon-set) in the Figma Community and export from there for Illustrator.
