### ISSUE TITLE
[Icon request] Improve icons for required/optional approved reviews

### ISSUE THREAD

**Issue by Andre601** [primer/octicons#590]
#### What should the icon represent?
The icon should be used to distinguish approved reviews that are required from those that are not.

#### Where will the icon be used?
On the sidebar of a Pull request is a section listing (pending) reviews.
When a user approves the changes is there a checkmark next to their name in the list. The issue here is, that there isn't any clear indicator of whether this approval is required for the PRs merging or not. The only difference to optional approvals/reviews is the fact, that the checkmark is green for required ones and grey for other ones.

For people suffering from Green/Red colour blindness can this cause issues as there is no clear way for them to know if a review is required or not.
Unless GitHub already offers something to fix this (I don't have color blindness so I can't know) should this icon be improved. Perhaps have two checkmarks next to each other for required approvals would be a solution?

#### Screenshots
![example of approval icons for reviews](https://user-images.githubusercontent.com/11576465/113929866-d5368f80-97f0-11eb-9734-444c6c7731c5.png)

**Comment by ashygee** [comment]
Hey @Andre601! Thanks for the icon request. I'm going to close this issue for now as this feels much greater than a request that a sole icon can solve and more of a consideration for how GitHub should showcase required reviewers within the platform itself. This is something we'd like to be intentional with how we want to find a solution rather than just creating a specific icon for this.
