### ISSUE TITLE
[Feedback] Change new issue-closed icon to make it more unique

### ISSUE THREAD

**Issue by Andre601** [primer/octicons#632]
### Describe the topic

The new issue-closed icon is... lazy to put it like that.
While I'm not an expert with images did I notice directly that the icon is essentially a copy-paste of the `check-circle` one.
[I already mentioned this](https://github.com/primer/octicons/pull/614#issuecomment-841683782) and even [made a comparison](https://user-images.githubusercontent.com/11576465/118371020-be7f1780-b5aa-11eb-866e-6d3497f114c9.png) (By hand!) to prove my point.

I would now like to suggest to revert the icon back to the old one, where a checkmark was at the edge of the circle. To make it match better with the other new icons (which are fine by me) should the exclamation be replaced by the dot to make it fit.

The icon as of now is just sad to look at, especially if you know this little secret. The old icon was perfectly fine and was easy enough to look at and understand.

### Anything else?

This is obviously a minor nitpick and I won't stop using GitHub because of this. But it just makes me sad that an icon set uses the same icon twice for two different things, while the same Icon could've been used to save space (Yes, SVG don't take up much space, but it's still extra space used for the same icon)

**Comment by ashygee** [comment]
Hi @Andre601, thanks for sharing your feedback. To get the new icons out we wanted to do this with as little change to the actual platform while we continue to iterate and continue to improve Octicons for GitHub. We are aware that it is the same glyph as what is used in `check-circle` and in future releases we will be sure to clean this up so that we don't house the same icon twice within our set.
